from typing import Protocol


class DAC(Protocol):
    def setup(self) -> None: ...

    def set_volume(self, volume: float) -> bool: ...

    def set_mute_on(self) -> bool: ...

    def set_mute_off(self) -> bool: ...

    def is_muted(self) -> bool: ...

    @property
    def enabled(self) -> bool: ...

    @property
    def volume(self) -> float: ...
