
pcm.satellite1_playback {
    type plug
    slave {
      pcm "hw:Satellite1,0"
      format S32_LE
      rate 48000
      channels 2
    }
}
pcm.satellite1_capture {
    type plug
    slave {
      pcm "hw:Satellite1,1"
      format S32_LE
      rate 48000
      channels 2
    }
}

#
# Default devices
#
pcm.!default {
    type asym
    playback.pcm "satellite1_playback"
    capture.pcm "satellite1_capture"
}

#
# Control mixer
#
ctl.!default {
    type hw
    card "Satellite1"
}

#
# Global defaults for better resampling
#
defaults.pcm.rate_converter "samplerate_best"
